name: CMake

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      matrix:
        build_type: [Release, Debug]
        generator: ["Unix Makefiles", "Ninja"]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install deps
      run: sudo apt-get install -y libeigen3-dev

    - name: Install ninja
      if: matrix.generator == 'Ninja'
      run: sudo apt-get install -y ninja-build

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build
           -G"${{ matrix.generator }}" \
           -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}

    - name: Build
      run: cmake --build ${{github.workspace}}/build

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -LE "^benchmark$"
      
